
export const CATEGORIES_LIST = [
  { id: 'Домашен майстор', label: 'Домашен майстор', labelKey: 'cat_handyman', icon: '🛠️' },
  { id: 'ВиК Услуги', label: 'ВиК Услуги', labelKey: 'cat_plumbing', icon: '🚰' },
  { id: 'Електро услуги', label: 'Електро услуги', labelKey: 'cat_electrician', icon: '⚡' },
  { id: 'Строителство', label: 'Строителство', labelKey: 'cat_construction', icon: '🧱' },
  { id: 'Почистване', label: 'Почистване', labelKey: 'cat_cleaning', icon: '🧹' },
  { id: 'Монтаж на мебели', label: 'Монтаж на мебели', labelKey: 'cat_furniture', icon: '🪑' },
  { id: 'Боядисване', label: 'Боядисване', labelKey: 'cat_painting', icon: '🎨' },
  { id: 'Ключарски услуги', label: 'Ключар', labelKey: 'cat_locksmith', icon: '🔑' },
  { id: 'Транспорт', label: 'Транспорт & Хамали', labelKey: 'cat_transport', icon: '🚚' },
  { id: 'Пътна помощ', label: 'Пътна помощ', labelKey: 'cat_roadside', icon: '🆘' },
  { id: 'Авто услуги', label: 'Авто услуги', labelKey: 'cat_auto', icon: '🔧' },
  { id: 'Автомивка', label: 'Автомивка', labelKey: 'cat_carwash', icon: '🚗' },
  { id: 'Ремонт на техника', label: 'Ремонт на техника', labelKey: 'cat_tech', icon: '📺' },
  { id: 'IT Услуги', label: 'IT & Програмиране', labelKey: 'cat_it', icon: '💻' },
  { id: 'Дизайн', label: 'Дизайн & Маркетинг', labelKey: 'cat_design', icon: '🖌️' },
  { id: 'Уроци', label: 'Уроци & Курсове', labelKey: 'cat_lessons', icon: '📚' },
  { id: 'Преводи', label: 'Преводи & Текстове', labelKey: 'cat_translation', icon: '📝' },
  { id: 'Красота', label: 'Красота & Здраве', labelKey: 'cat_beauty', icon: '💅' },
  { id: 'Спорт', label: 'Спорт & Тренировки', labelKey: 'cat_sport', icon: '💪' },
  { id: 'Гледане на деца', label: 'Гледане на деца', labelKey: 'cat_babysitting', icon: '🧸' },
  { id: 'Домашни любимци', label: 'Домашни любимци', labelKey: 'cat_pets', icon: '🐶' },
  { id: 'Градинарство', label: 'Градинарство', labelKey: 'cat_gardening', icon: '🌳' },
  { id: 'Събития', label: 'Събития & Парти', labelKey: 'cat_events', icon: '🎉' },
  { id: 'Фотография', label: 'Фото & Видео', labelKey: 'cat_photo', icon: '📸' },
  { id: 'Счетоводство', label: 'Счетоводство & Право', labelKey: 'cat_finance', icon: '⚖️' },
  { id: 'Други', label: 'Други', labelKey: 'cat_other', icon: '📦' }
];
